openapi: 3.0.3
info:
    title: Chatter service describing the streaming features of goa v2.
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for chatter
paths:
    /subscribe:
        get:
            tags:
                - chatter
            summary: subscribe chatter
            description: Subscribe to events sent when new chat messages are added.
            operationId: chatter#subscribe
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SubscribeResponseBody'
                            example:
                                payload:
                                    Type: ping_event
                                    Value: '"JSON"'
components:
    schemas:
        SubscribeResponseBody:
            type: object
            properties:
                payload:
                    type: object
                    properties:
                        Type:
                            type: string
                            description: |-
                                Union type name, one of:
                                - "ping_event"
                                - "foobar_event"
                            example: ping_event
                            enum:
                                - ping_event
                                - foobar_event
                        Value:
                            type: string
                            description: JSON formatted union value
                            example: '"JSON"'
                    example:
                        Type: ping_event
                        Value: '"JSON"'
                    required:
                        - Type
                        - Value
            description: SubscribeResponseBody result type (default view)
            example:
                payload:
                    Type: ping_event
                    Value: '"JSON"'
tags:
    - name: chatter
      description: The chatter service implements a simple client and server chat.
